# Generated by Django 5.0.4 on 2024-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='loc',
            field=models.CharField(max_length=30),
        ),
    ]
